tls-cert-path:
tls-key-path:
addr: :39252
backport-path: /etc/qrystal/cs-backport.yml
db-path: /etc/qrystal/db
tokens:
  - name: master
    hash: …
    can-add-tokens:
      can-pull: true # required to add tokens with can-pull: true
  - name: phone0
    hash: …
    can-pull: true
    networks:
      examplenet: phone
  - name: desktop0
    hash: …
    can-pull: true
    # if can-push: true and networks is not blank, can-push can only push e.g.
    # peer desktop to network examplenet.
    can-push: true
    networks:
      examplenet: desktop
central:
  networks:
    examplenet:
      keepalive: 10s
      listen-port: 58120
      ips:
        - 10.123.0.1/16
      peers:
        phone:
          allowed-ips:
            - 10.123.0.1/32
        desktop:
          allowed-ips:
            - 10.123.0.2/32
