# Private key of this Node. Generate using qrystal-gen-keys.
private-key: <node-private-key>
css:
  - comment: main server
    # endpoint: <cs-host>:39252
    # tls-cert-path: /etc/cs.pem
    # networks: allowed network names
    token: # required central token
