css:
  # Friendly name for CS
  comment:
  # Endpoint to CS
  endpoint:
  tls:
    # Path to TLS certificate.
    certPath:
  # Networks to pull from CS.
  networks: [ <peer name>… ]
  # Path to file containing Central Token.
  tokenPath:
  # Central Token itself.
  token:
  # Push peer to net before pulling.
  azusa:
    networks:
      <net name>:
        # Peer name to push to.
        name:
        # Endpoint= in wg-quick config
        host:
        # AllowedIPs= in wg-quick config
        allowed-ips:
          - 10.123.0.1/32
        # peer can only see the following peers
        canSee:
          only: [ <peer name>… ]
