# Private key of this Node. Generate using qrystal-gen-keys.
private-key: <node-private-key>
server:
  # Address of Node gRPC server.
  addr: :39251
  tls-cert-path:
  tls-key-path:
# Central configuration (note that this will be overridden by CS if applicable).
central:
cs:
  host: <qrystal-cs>:39252
  token: <token>
# Automatically push nodes onto networks using cs.
azusa:
  networks:
    <some-network>: <peer-name>
