mio:
  subprocess:
    # Mio sets WireGuard configs so needs to be root for this machine (using Linux kernel impl).
    path: /opt/qrystal/runner-mio
    credential:
      user: root
      group: root
node:
  config-path: /etc/qrystal/node-config.yml
  working-dir: /opt/qrystal
  subprocess:
    path: /opt/qrystal/runner-node
    credential:
      user: qrystal-node
      group: qrystal-node
