name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Docker Build
      run: ./build-docker.sh
      id: build

    - name: Archive
      run: tar czvf ./build2.tar.gz ./build2

    - name: Upload Docker Build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./build2.tar.gz
