name: パッケージ化

on:
  push:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: makepkg
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
    - name: Upload Package Archive
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
